service: serverless-ensemble-lambda

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  tracing: true
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
      - Fn::Join:
        - ':'
        - - arn:aws:lambda
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - function:${self:service}-${opt:stage, self:provider.stage}-*
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

plugins:
  # - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-offline-scheduler
  - serverless-plugin-warmup
  - serverless-plugin-tracing

custom:
  warmup:
    enabled: true
    prewarm: true
    events:
      - schedule: rate(5 minutes)
    payload: warmup
    concurrency: 5

functions:
  api:
    handler: dist/app.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
