on:
  push:
    tags:
    - 'v*.*.*'
jobs:
  serverless-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 12
      - run: npm i -g yarn
      - run: yarn install
      - run: yarn deploy:credentials --provider aws --key ${{secrets.AWS_ACCESS_KEY_ID}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - run: |
          echo "DB_URL=${{secrets.DB_URL}}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{secrets.JWT_SECRET}}" >> $GITHUB_ENV
      - run: yarn build
      - run: yarn deploy --stage prod
